### PR TITLE
Avoid image urls on search results

### PR DESCRIPTION
**Pull request by heron2014**
One way of resolving this [issue 12](https://github.com/akitten/public-profile-page-url-finder/issues/12)

### CODE REVIEW

**Comment by nelsonic** [comment]
@heron2014 are you adding anything else to this PR or is it ready to be merged?

**Comment by heron2014** [comment]
@nelsonic yes, no more addition. It's ready to merge.

**Comment by nelsonic** [comment]
Version `1.0.9` has been published to NPM!
Thanks. :+1:

**Comment by heron2014** [comment]
Awesome :cocktail: !!

**Pull request merged**
