### PR TITLE
return error when statusCode is not 200

### PR DESCRIPTION
**Pull request by SimonLab**
resolve [issue 20](https://github.com/akitten/public-profile-page-url-finder/issues/20) : return error if statusCode is not 200

resolve [issue 21](https://github.com/akitten/public-profile-page-url-finder/issues/21) : do not save file at each query.

@nelsonic Do you mind to check this PR?

### CODE REVIEW

**Comment by nelsonic** [comment]
Looks good. :+1: 
Merging.

**Comment by nelsonic** [comment]
New version on NPM: `1.1.1` :+1:

**Comment by SimonLab** [comment]
1.1.2

**Comment by nelsonic** [comment]
correct. silly me. https://github.com/akitten/public-profile-page-url-finder/blob/f5e5e200605d0edad373e2a37d1ad88046d2fdb3/package.json#L3

**Pull request merged**
