### PR TITLE
avoid adverts

### PR DESCRIPTION
**Pull request by heron2014**
See [issue 16](https://github.com/akitten/public-profile-page-url-finder/issues/16)

### CODE REVIEW

**Comment by nelsonic** [comment]
@heron2014 is this ready?
It does not *look* like there are *multiple* test cases...
Let me know if you need any help. 
(*hope your day is going well*)

**Comment by heron2014** [comment]
I think it's ready:
We have one test that checks we are not taking the urls from google results with adverts. Can you please explain what did you mean by multiple cases? Is this test not enough?

**Comment by nelsonic** [comment]
Having a *single* test per "feature" is "*okay*" but you *really* want to have *a few* test cases.
Also, http://semver.org/ the `PATCH` version can go up *indefinitely* ... 9 is not the max.

**Comment by heron2014** [comment]
@nelsonic I will fix the version :blush:  and also I will try to do more tests on this feature.

**Comment by nelsonic** [comment]
@heron2014 I'm *happy* to merge the change so you can get on with your work, just want to encourage more tests so you *know* it works as you expect it to.
Let me know when to merge. :+1:

**Comment by heron2014** [comment]
Yes please! I will try to improve the tests asap.  :)

**Comment by edwardcodes** [comment]
Looks good.

**Comment by nelsonic** [comment]
Thanks for checking/merging @edwardcodes :+1: 
I've published the latest version on NPM: `1.1.0`

**Comment by nelsonic** [comment]
kitten

**Pull request merged**
